application: wikiflashcard
version: dev
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: latest
- name: numpy
  version: latest
- name: lxml
  version: latest

handlers:
- url: /.*
  script: app.app
- url: /static
  static_dir: static

skip_files:
- ^(.*/)?module\.yaml
- ^(.*/)?module\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^test/.*
- ^bin/.*
- ^include/.*
- ^lib/python.*
- ^share/.*
